### ISSUE TITLE
rework transport.dial to dial addresses in parallel 

### ISSUE THREAD

**Issue by dryajov** [libp2p/js-libp2p-swarm#194]
- use async.queue with a concurrency of e.g 4
- push all addrs as task to the queue
- start the queue
- in the worker function check if success and if so call queue.kill and the callback
- if after finishing the queue no success happened call back in with an error

Initially discussed here - https://github.com/libp2p/js-libp2p-swarm/pull/193
Needed to fix this - https://github.com/ipfs/js-ipfs/issues/812

**Comment by dignifiedquire** [comment]
Reference in go: https://github.com/libp2p/go-libp2p-swarm/blob/master/limiter.go
