### ISSUE TITLE
swam leaves nodes in peerbook after disconnect

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-swarm#221]
seems like it should happen approximately here
https://github.com/libp2p/js-libp2p-swarm/blob/master/src/dial.js#L163

**Comment by kumavis** [comment]
@diasdavid please confirm and I can PR

**Comment by dignifiedquire** [comment]
I belive this is on purpose to collect seen addresses over time as the dht uses this to store info on seen peers.

**Comment by kumavis** [comment]
perhapos true - let me restate the problem: `ipfs.swarm.peers` returns non-connected peers

**Comment by kumavis** [comment]
should prolly check for activce connections here
https://github.com/ipfs/js-ipfs/blob/master/src/core/components/swarm.js#L26-L47

**Comment by kumavis** [comment]
oh interesting - seems like we do this on `ipfs.swarm.addrs`
https://github.com/ipfs/js-ipfs/blob/master/src/core/components/swarm.js#L56

this seems backwards, doesnt it?

**Comment by diasdavid** [comment]
Yes, we leave the peers in PeerBook, this way we can reuse addrs (and it is a step towards dumping peer lists for later boots).

To see if we are actually connected, we have an isConnected on PeerInfo https://github.com/libp2p/js-peer-info/blob/master/src/index.js#L20-L26

Nevertheless, you did find a bug, swarm.peers should be checking, in the same way, that swarm.addrs is https://github.com/ipfs/js-ipfs/blob/master/src/core/components/swarm.js#L56

@kumavis wanna submit a fix? Thanks for finding this!

**Comment by kumavis** [comment]
@diasdavid sure, happy to submit a PR. one more clarification - should `swarm.addrs` be doing the isConnected filtering?

**Comment by diasdavid** [comment]
Seems somehow, when that got changed, there was a confusion and the .isConnected was applied in swarm.addrs, where it had to be _only_ in swarm.peers.

![image](https://user-images.githubusercontent.com/1211152/27948262-1ff8ce7c-62f1-11e7-826e-7b475e991736.png)
