### ISSUE TITLE
Change "let" to "var".

### ISSUE THREAD

**Issue by alexsicart** [libp2p/js-libp2p-swarm#232]
I'm using Angular 4 for https://decentralized.cloud/, when trying to go to production mode, it gives me a problem with ES6 code. let is  ES6, so it gives me several problems. This problem is in js-libp2p-swarm/src/get-peer-info.js line 11. Where there is a let.

Thanks!

**Comment by dryajov** [comment]
Could you provide more details as to what your environment looks like? 

- is it being built with webpack/browserify or using a prebuild version from a cdn? 
- does this error happen in the browser (which one) or nodejs (version)?

IPFS uses some es6 features extensively - class, =>, let/const, etc... some environments might require transpilation, but in general the subset used is well supported by recent browsers and nodejs.

**Comment by diasdavid** [comment]
@alexsicart I'm figuring that since you have been using js-ipfs for a while that this isn't a issue anymore. Going to close it, let me know if I got it wrong :)
