### ISSUE TITLE
Handle non existing peers in identify

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-swarm#75]
Sometimes this error is thrown

```
Uncaught TypeError: Cannot read property 'conn' of undefined
```

which originates from [here](https://github.com/diasdavid/js-libp2p-swarm/blob/master/src/identify.js#L93). We should handle peers going away while identify is happening and close gracefully rather than just failing

**Comment by dignifiedquire** [comment]
cc @diasdavid

**Comment by diasdavid** [comment]
@dignifiedquire can you verify this still applies with all the new pull-streams upgrades?

**Comment by dignifiedquire** [comment]
I haven't seen this error once in all them tests. Lets eait until we have things running in js-ipfs & orbit to see if this is still an issue.

**Comment by dignifiedquire** [comment]
I don't think this is still an issue, closing.

**Comment by diasdavid** [comment]
:+1:
