### ISSUE TITLE
Decentralized communication with p2p, express, angular and node js

### ISSUE THREAD

**Issue by varunagarwal315** [libp2p/js-libp2p-swarm#81]
Extremely sorry if this is the wrong place for such a post but I had no where else to go.

I am trying to find a way to combine ipfs with javascript.

A `GET` request to `localhost:8000` returns index.html which has a button on it. When clicked, a `POST` request is sent to `localhost:8000/recieve`, the data is processed and sent via a  `node` using this library. That node dials to a different node setup elsewhere, which will process the data further.

Here comes the tricky part. Based on the data processed by the second node, the user has to be shown a message. Sending information back from node2 to node1 is easy as the communication is already setup using functions from lib p2p but final communication with the user is something that has driven me crazy.

I know this is not an issue as such, but any and all help will be highly appreciated. Thanks in advance! Quick summary

GET request --> index.html --> user clicks a button --> data from a form sent via POST to server setup via express --> data processed using body parser --> JSON data communicated between nodes setup by lib p2p --> node 2 processes data and sends response back to node 1 --> ???? --> User sees some action on index.html

**Comment by diasdavid** [comment]
Hi @varunagarwal315, the right place to ask for support is on our support repo https://github.com/ipfs/support, this repo is for libp2p-swarm, a module part of the network stack, could you reopen the issue there.

Nevertheless, looking at the issue, seems that you want to use the HTTP-API, which is available by default at port 5001 and not at port 8080, port 8080 is just a read only gateway (does not accept POST). Still, if you can present a way to replicate your problem easier, will be easier to provide help.

Closing this one here, please open in https://github.com/ipfs/support
