### ISSUE TITLE
dialables function in transport makes little sense

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-swarm#85]
This code : https://github.com/libp2p/js-libp2p-swarm/blob/master/src/transport.js#L145-L151 is very odd as it seems to be doing the same thing no matter how the `if` evaluates.

@diasdavid could you check this please.

**Comment by OnlyBird** [comment]
```
function dialables (tp, multiaddrs) {
  return tp.filter(multiaddrs.map((addr) => {
    // webrtc-star needs the /ipfs/QmHash
    if (addr.toString().indexOf('webrtc-star') > 0) {
      return addr
    }

    return addr
  }))
}
```

This second `return addr` after the if statement means that the variable `addr` is returned with or without the `if` statement being present. As it stands you could completely remove the `if` statement and the same result would be yielded, I hope this helps a little - I don't have the time to go all the way through your code right now to suggest an alternative piece of code for your problem.

**Comment by dignifiedquire** [comment]
Thanks @OnlyBird as far as I understand it it could be reduced to 

```js
function dialables (tp, multiaddrs) {
  return tp.filter(multiaddrs)
}
```

which is why I pinged @diasdavid to check it out as he wrote the `webrtc-star` comment

**Comment by diasdavid** [comment]
@dignifiedquire It this causing a bug? It should be just a leftover, because before transports didn't know how to get rid of the /ipfs/QmHash themselves and now they do. This function was filtering out the /ipfs/QmHash, but since libp2p-webrtc-star uses them, we made sure not to filter if the transport was webrtc-star

**Comment by dignifiedquire** [comment]
Well it's technically not a bug as it stands, just an inefficiency. The question is should something happen here still or is that not needed anymore

**Comment by diasdavid** [comment]
@dignifiedquire feel free to go ahead and clean it up  :)

**Comment by dignifiedquire** [comment]
Fixed
