### ISSUE TITLE
Replace lodash.contains with lodash.includes

### ISSUE THREAD

**Issue by ChALkeR** [libp2p/js-libp2p-swarm#89]
[lodash.contains](https://www.npmjs.com/package/lodash.contains) has a huge deps tree that adds some install time, and it was deprecated, with the last release over 1½ years ago.

It should be replaced with [lodash.includes](https://www.npmjs.com/package/lodash.includes).

Related: https://github.com/lodash/lodash-cli/issues/120.

**Comment by dignifiedquire** [comment]
Thanks for the notice. Want to create a PR?

**Comment by ChALkeR** [comment]
@dignifiedquire Sorry, no PR here — that requires testing, which I probably currently can't do =).
